#!/bin/bash
printf "%s\n" ./* | sed -e 's/[^[:alnum:]]/\n/g' | sort -f | awk '{if ($0 ~ /^\.$/) print; else if ($0 ~ /^\.\.$/) print; else if ($0 ~ /\/$/) print; else print $0;}' | tr '\n' ',' && echo



